name: Publish Package to npmjs
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - if: ${{contains(matrix.os, 'windows')}}
        uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: amd64
      - uses: lukka/get-cmake@v3.30.0
      - if: ${{contains(matrix.os, 'ubuntu')}}
        uses: awalsh128/cache-apt-pkgs-action@v1.4.2
        with:
          packages: libc6-dev
      - name: Install CUDA (Linux)
        env:
          cuda: "12.5.1"
        if: ${{contains(matrix.os, 'ubuntu')}}
        run: ./cuda-cmake-github-actions/scripts/actions/install_cuda_ubuntu.sh
        shell: bash
      - name: Install CUDA (Windows)
        env:
          cuda: "12.5.1"
          visual_studio: "Visual Studio 17 2022"
        if: ${{contains(matrix.os, 'windows')}}
        run: ./cuda-cmake-github-actions/scripts/actions/install_cuda_windows.ps1
        shell: powershell
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npx pkg-prebuilds-copy --baseDir build/Release --source node-stable-diffusion-cpp.node --name=node-stable-diffusion-cpp --strip  --napi_version=9 --arch=x64 ${{ contains(matrix.os, 'windows') && '--extraFiles=cublas64_12.dll --extraFiles=cublasLt64_12.dll' || '' }}
      - uses: actions/upload-artifact@v4
        with:
          name: node-addon-binary-${{ matrix.os }}
          path: prebuilds/
          retention-days: 1

  publish:
    needs:
      - build
    runs-on: ubuntu-22.04
    environment: "NPM Publish"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - uses: actions/download-artifact@v4
        with:
          pattern: node-addon-binary-*
          path: prebuilds
          merge-multiple: true
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: node-addon-binary-*
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm pack
      - uses: actions/upload-artifact@v4
        with:
          name: lmagder-node-stable-diffusion-cpp
          path: lmagder-node-stable-diffusion-cpp-*.tgz
